### ISSUE TITLE
Installed app not listed

### ISSUE THREAD

**Issue by C-O-D** [aj-white/piplexed#69]
I have installed the app 'tidal-dl-ng' normally with 'pipx install tidal-dl-ng[gui]', but i don't get it listed with 'piplexed list' - what could be the reason?

**Comment by aj-white** [comment]
Hi, thanks for reaching out, do you get the app listed when you run `pipx list` ?
If it doesn't show then there maybe an issue with the `pipx install` ?

If it does show, then would you be able to provide a little more information so I can have a look.
- Version of piplexed (run `piplexed version`)
- Version of pipx (run `pipx --version`)
- Which operating system
- The location that pipx puts the apps in (PIPX_LOCAL_VENVS value from running `pipx environment`)

Thanks.

**Comment by C-O-D** [comment]
hi, thanks for responding - yes, the app is listed with `pipx list` and I would say it's installed from PyPI.
OS is Manjaro 24.1.2 and here's the additional info:

pipx list
venvs are in /home/cod/.local/share/pipx/venvs
apps are exposed on your $PATH at /home/cod/.local/bin
manual pages are exposed at /home/cod/.local/share/man
   package piplexed 0.6.1, installed using Python 3.12.6
    - piplexed
   package tidal-dl-ng 0.20.3, installed using Python 3.12.6
    - tdn
    - tdng
    - tidal-dl-ng
    - tidal-dl-ng-gui

piplexed version
0.6.1

pipx --version
1.6.0

pipx environment
Environment variables (set by user):

PIPX_HOME=
PIPX_BIN_DIR=
PIPX_MAN_DIR=
PIPX_SHARED_LIBS=
PIPX_DEFAULT_PYTHON=
PIPX_FETCH_MISSING_PYTHON=
USE_EMOJI=

Derived values (computed by pipx):

PIPX_HOME=/home/cod/.local/share/pipx
PIPX_BIN_DIR=/home/cod/.local/bin
PIPX_MAN_DIR=/home/cod/.local/share/man
PIPX_SHARED_LIBS=/home/cod/.local/share/pipx/shared
PIPX_LOCAL_VENVS=/home/cod/.local/share/pipx/venvs
PIPX_LOG_DIR=/home/cod/.local/state/pipx/log
PIPX_TRASH_DIR=/home/cod/.local/share/pipx/trash
PIPX_VENV_CACHEDIR=/home/cod/.cache/pipx
PIPX_STANDALONE_PYTHON_CACHEDIR=/home/cod/.local/share/pipx/py
PIPX_DEFAULT_PYTHON=/usr/bin/python3.12
USE_EMOJI=true

**Comment by C-O-D** [comment]
piplexed list
                 Pip❎ Packages                 
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ Package Name ┃ Pipx Version ┃ Python Version ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━┩
│     piplexed │        0.6.1 │         3.12.6 │
└──────────────┴──────────────┴────────────────┘

**Comment by aj-white** [comment]
Thanks for that, the local venv path looks fine and given that `piplexed list` is returning piplexed, that means we are finding the venvs correctly.
My next thought would be, piplexed uses the *pipx_metadata.json* file, generated by pipx on install to get the python version, package version and determine if the package is installed from PyPI or not. Inside the `pipx/venvs` folder there will be the `tidal-dl-ng` folder and in that should be the *pipx_metadata.json* file, would you be able to post that here, as it maybe that there is a scenario piplexed is not accounting for.

**Comment by C-O-D** [comment]
No problem, here it is:
[pipx_metadata.json](https://github.com/user-attachments/files/17874242/pipx_metadata.json)

**Comment by C-O-D** [comment]
Is something missing?

**Comment by aj-white** [comment]
I understand what's happened. Usually when a package is installed from pypi the `package` and `package_or_url` metadata is identical. Piplexed used this as a simple check to prevent non-pypi packages being checked for pypi details. It turns out that when a package is installed with optional extras, `package` is the *package_name* and `package_or_url` is *package_name[extras]*, as they don't match piplexed doesn't pick them up, which is what happened in this case.

Piplexed was originally designed for checking for newer pypi packages, howevere I think it is more sensible for `piplexed list` to show all packages installed and let the --outdated flag handle pypi only packages. I'll remove the check and handle non-pypi packages later in the process.
Hopefully get a fix out this week, thanks for raising the issue.

**Comment by C-O-D** [comment]
Sounds good, many thanks!
